language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "nightly"

env:
  - CONTAO_VERSION=~3.5.0

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

matrix:
  allow_failures:
    - php: "7.0"
    - php: "nightly"

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647
